"use server";

import { revalidatePath } from "next/cache";
import { db } from "@/lib/db";
import { requireAdminSession } from "@/lib/auth";
import { Platform, TaskType, InvitationStatus, LedgerStatus } from "@prisma/client";

const VALID_PLATFORMS = new Set(Object.values(Platform));
const VALID_TYPES = new Set(Object.values(TaskType));

export type AdhocCollabState = { error?: string; success?: string };

/**
 * Ad-hoc collab, posted directly by an admin rather than generated by
 * lib/matching-engine.ts from a brand's budget/criteria. Has no brand
 * behind it (Task.brandId is null) — exists purely to seed creator
 * engagement before real brands have signed up. Bypasses the persona
 * gate and diversified selection entirely: the admin hand-picks exactly
 * who gets it. `payoutAmount` is the max per-creator rate; `maxBudget`
 * is a dispatch-time cap only (not persisted) — it isn't a real spend
 * ceiling on anything, just guards against fat-fingering more
 * recipients than intended.
 */
export async function createAdhocCollab(
  _prevState: AdhocCollabState,
  formData: FormData
): Promise<AdhocCollabState> {
  const admin = await requireAdminSession();
  if (!admin) return { error: "Not signed in." };

  const typeRaw = String(formData.get("type") ?? "");
  const type = VALID_TYPES.has(typeRaw as TaskType) ? (typeRaw as TaskType) : TaskType.UGC_VIDEO;
  const platformRaw = String(formData.get("platform") ?? "INSTAGRAM");
  const platform = VALID_PLATFORMS.has(platformRaw as Platform)
    ? (platformRaw as Platform)
    : Platform.INSTAGRAM;
  const description = String(formData.get("description") ?? "").trim();
  const verificationTag = String(formData.get("verificationTag") ?? "").trim() || null;
  const targetPostUrl = String(formData.get("targetPostUrl") ?? "").trim() || null;
  const maxBudget = Number(formData.get("maxBudget") ?? 0);
  const payoutAmount = Number(formData.get("payoutAmount") ?? 0);
  const influencerIds = formData.getAll("influencerIds").map(String);

  if (!description) {
    return { error: "Write additional instructions." };
  }
  if (!Number.isFinite(payoutAmount) || payoutAmount <= 0) {
    return { error: "Per-creator payout must be a positive number." };
  }
  if (!Number.isFinite(maxBudget) || maxBudget <= 0) {
    return { error: "Max budget must be a positive number." };
  }
  if (influencerIds.length === 0) {
    return { error: "Select at least one creator to send this to." };
  }
  const maxCreators = Math.floor(maxBudget / payoutAmount);
  if (influencerIds.length > maxCreators) {
    return {
      error: `${influencerIds.length} creators selected, but a $${maxBudget} budget at $${payoutAmount}/creator only covers ${maxCreators}.`,
    };
  }

  const task = await db.task.create({
    data: {
      brandId: null,
      type,
      platform,
      description,
      payoutAmount,
      verificationTag: type === TaskType.UGC_VIDEO ? verificationTag : null,
      targetPostUrl: type === TaskType.UGC_VIDEO ? null : targetPostUrl,
    },
  });

  await db.taskInvitation.createMany({
    data: influencerIds.map((influencerId) => ({ taskId: task.id, influencerId })),
  });

  revalidatePath("/admin");
  return {
    success: `Dispatched to ${influencerIds.length} creator${influencerIds.length === 1 ? "" : "s"}.`,
  };
}

/**
 * The only way a Like/Share collab (or anything else stuck on a real
 * verification failure) ever gets paid — there's no automated path for
 * those, by design (see the TaskType comment in schema.prisma). Plain
 * form-action, not useActionState — this is a one-click admin override,
 * not a form with its own validation state.
 */
export async function markInvitationCredited(formData: FormData) {
  const admin = await requireAdminSession();
  if (!admin) return;

  const invitationId = String(formData.get("invitationId") ?? "");
  const invitation = await db.taskInvitation.findUnique({
    where: { id: invitationId },
    include: { task: true },
  });
  if (!invitation) return;
  if (
    invitation.status !== InvitationStatus.SUBMITTED &&
    invitation.status !== InvitationStatus.VERIFYING
  ) {
    return;
  }

  await db.$transaction([
    db.taskInvitation.update({
      where: { id: invitationId },
      data: { status: InvitationStatus.CREDITED },
    }),
    db.walletLedgerEntry.update({
      where: { invitationId },
      data: { status: LedgerStatus.CREDITED },
    }),
    db.influencer.update({
      where: { id: invitation.influencerId },
      data: { walletBalance: { increment: invitation.task.payoutAmount } },
    }),
  ]);

  revalidatePath("/admin");
}
